server:
  port: 12100

management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      enable: true
      show details: always
    beans:
      enable: true
    info:
      enabled: true
  server:
    address: localhost
    port: 12101

poly: 'BigData Dev!'